//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAVN.Service.Campaign.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAVN.Service.Campaign.Strings.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign completion must be either null or greater than 0..
        /// </summary>
        public static string CampaignCompletionMin {
            get {
                return ResourceManager.GetString("CampaignCompletionMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign must have at least one Condition.
        /// </summary>
        public static string CampaignConditionNotNull {
            get {
                return ResourceManager.GetString("CampaignConditionNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign must not have two or more Conditions of same type.
        /// </summary>
        public static string CampaignConditionUnique {
            get {
                return ResourceManager.GetString("CampaignConditionUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign From Date is Required.
        /// </summary>
        public static string CampaignFromDateRequired {
            get {
                return ResourceManager.GetString("CampaignFromDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign From Date must be a present or a future date.
        /// </summary>
        public static string CampaignFromDateValidation {
            get {
                return ResourceManager.GetString("CampaignFromDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Id is Required.
        /// </summary>
        public static string CampaignIdRequired {
            get {
                return ResourceManager.GetString("CampaignIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Reward must be greater than or equal to 0.
        /// </summary>
        public static string CampaignRewardGreaterOrEqualToZero {
            get {
                return ResourceManager.GetString("CampaignRewardGreaterOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign To Date must be after From Date.
        /// </summary>
        public static string CampaignToBeforeFromDateValidation {
            get {
                return ResourceManager.GetString("CampaignToBeforeFromDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign To Date must be a present or a future date.
        /// </summary>
        public static string CampaignToDateValidation {
            get {
                return ResourceManager.GetString("CampaignToDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Completion Count must be null or greater than 0.
        /// </summary>
        public static string ConditionCompletionCountValidation {
            get {
                return ResourceManager.GetString("ConditionCompletionCountValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign completion count must me either null or less than 2147483647..
        /// </summary>
        public static string ConditionCompletionMax {
            get {
                return ResourceManager.GetString("ConditionCompletionMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Id is Required.
        /// </summary>
        public static string ConditionIdRequired {
            get {
                return ResourceManager.GetString("ConditionIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Immediate Reward must be greater than or equal 0.
        /// </summary>
        public static string ConditionImmediateRewardValidation {
            get {
                return ResourceManager.GetString("ConditionImmediateRewardValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid entity.
        /// </summary>
        public static string EntityNotValid {
            get {
                return ResourceManager.GetString("EntityNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with id {1} was not found.
        /// </summary>
        public static string EntityWithIdNotFound {
            get {
                return ResourceManager.GetString("EntityWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed invalid content type.
        /// </summary>
        public static string InvalidContentType {
            get {
                return ResourceManager.GetString("InvalidContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Identifier.
        /// </summary>
        public static string InvalidIdentifier {
            get {
                return ResourceManager.GetString("InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} length should be between {1} and {2} characters.
        /// </summary>
        public static string LengthBetweenValidation {
            get {
                return ResourceManager.GetString("LengthBetweenValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed file is not a valid type.
        /// </summary>
        public static string NotValidFormatFile {
            get {
                return ResourceManager.GetString("NotValidFormatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested combination of ({CurrentPage} - 1) * {PageSize} can&apos;t be more than {IntMax}.
        /// </summary>
        public static string PaginationCurrentMax {
            get {
                return ResourceManager.GetString("PaginationCurrentMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page can&apos;t be less than 1 or greater than {0}.
        /// </summary>
        public static string PaginationCurrentPageValidation {
            get {
                return ResourceManager.GetString("PaginationCurrentPageValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size cannot exceed more then 500.
        /// </summary>
        public static string PaginationPageSizeMax {
            get {
                return ResourceManager.GetString("PaginationPageSizeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size can&apos;t be less than 1.
        /// </summary>
        public static string PaginationPageSizeMin {
            get {
                return ResourceManager.GetString("PaginationPageSizeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string RequiredValidation {
            get {
                return ResourceManager.GetString("RequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Content &apos;Description&apos; in English is mandatory.
        /// </summary>
        public static string RuleContentDescriptionNotNull {
            get {
                return ResourceManager.GetString("RuleContentDescriptionNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Content &apos;Title&apos; in English is mandatory.
        /// </summary>
        public static string RuleContentTitleNotNull {
            get {
                return ResourceManager.GetString("RuleContentTitleNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should have at least one English content.
        /// </summary>
        public static string RuleContentTypeNotNull {
            get {
                return ResourceManager.GetString("RuleContentTypeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should have only one content for &apos;type&apos; by localization.
        /// </summary>
        public static string RuleContentUnique {
            get {
                return ResourceManager.GetString("RuleContentUnique", resourceCulture);
            }
        }
    }
}
